version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run: pip install mypy
      - run: pip install pylint
      - run: pip install -e .
      - run: make unit-test
      - run: make ci-test
